# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jour_semaine', models.CharField(choices=[('LUNDI', 'Lundi'), ('MARDI', 'Mardi'), ('MERCREDI', 'Mercredi'), ('JEUDI', 'Jeudi'), ('VENDREDI', 'Vendredi')], max_length=20, verbose_name='Jour de la semaine')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du menu')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('plats', models.TextField(verbose_name='Plats')),
                ('est_disponible', models.BooleanField(default=True, verbose_name='Disponible')),
                ('quantite_disponible', models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantité disponible')),
                ('quantite_consomme', models.IntegerField(default=0, verbose_name='Quantité consommée')),
                ('prix', models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Prix')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menus/', verbose_name='Image du plat')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['restaurant', 'jour_semaine'],
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du restaurant')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('telephone', models.CharField(max_length=17, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('numero_enregistrement', models.CharField(blank=True, max_length=100, verbose_name="Numéro d'enregistrement")),
                ('numero_fiscal', models.CharField(blank=True, max_length=100, verbose_name='Numéro fiscal')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif'), ('SUSPENDU', 'Suspendu')], default='ACTIF', max_length=20, verbose_name='Statut')),
                ('en_service_actuel', models.BooleanField(default=False, verbose_name='En service actuellement')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='restaurants/logos/', verbose_name='Logo')),
                ('image_couverture', models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', verbose_name='Image de couverture')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Restaurant',
                'verbose_name_plural': 'Restaurants',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateField(verbose_name='Date de réservation')),
                ('quantite', models.IntegerField(default=1, verbose_name='Quantité')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('CONFIRME', 'Confirmé'), ('ANNULE', 'Annulé'), ('TERMINE', 'Complété')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.menu')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation', '-date_creation'],
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='restaurants.restaurant'),
        ),
        migrations.CreateModel(
            name='PlanningRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_planning', models.CharField(choices=[('HEBDOMADAIRE', 'Hebdomadaire'), ('MENSUEL', 'Mensuel')], max_length=20, verbose_name='Type de planning')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('agence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings_restaurant', to='accounts.agence')),
                ('cree_par', models.ForeignKey(limit_choices_to={'type_utilisateur__in': ['SUPER_ADMIN', 'CASHIER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plannings_crees', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Planning de Restaurant',
                'verbose_name_plural': 'Plannings de Restaurants',
                'ordering': ['-date_debut'],
                'unique_together': {('restaurant', 'agence', 'date_debut', 'date_fin')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='menu',
            unique_together={('restaurant', 'jour_semaine', 'date')},
        ),
    ]
