# Generated by Django 6.0.2 on 2026-02-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='numero_enregistrement',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='numero_fiscal',
        ),
    ]
