# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('restaurants', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogConsommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consommation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de consommation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_consommation', to='accounts.agence')),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='logs_consommation', to=settings.AUTH_USER_MODEL)),
                ('menu_consomme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_consommation', to='restaurants.menu')),
                ('qr_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_consommation', to='tickets.codeqr')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_consommation', to='restaurants.restaurant')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_consommation', to='tickets.ticket')),
                ('valide_par', models.ForeignKey(limit_choices_to={'type_utilisateur': 'RESTAURANT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consommations_validees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Consommation',
                'verbose_name_plural': 'Logs de Consommation',
                'ordering': ['-date_consommation'],
                'indexes': [models.Index(fields=['date_consommation'], name='transaction_date_co_c29d03_idx'), models.Index(fields=['client', 'date_consommation'], name='transaction_client__902647_idx'), models.Index(fields=['restaurant', 'date_consommation'], name='transaction_restaur_f3d31f_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransactionTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_transaction', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro de transaction')),
                ('type_transaction', models.CharField(choices=[('ACHAT', 'Achat'), ('REMBOURSEMENT', 'Remboursement')], default='ACHAT', max_length=20, verbose_name='Type')),
                ('nombre_tickets', models.IntegerField(verbose_name='Nombre de tickets')),
                ('premier_ticket', models.CharField(max_length=50, verbose_name='Numéro du premier ticket')),
                ('dernier_ticket', models.CharField(max_length=50, verbose_name='Numéro du dernier ticket')),
                ('valide_de', models.DateField(verbose_name='Valide à partir du')),
                ('valide_jusqu_a', models.DateField(verbose_name="Valide jusqu'au")),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix unitaire')),
                ('subvention_par_ticket', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subvention par ticket')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant total')),
                ('subvention_totale', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subvention totale')),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Mobile Money'), ('VIREMENT', 'Virement')], max_length=20, verbose_name='Mode de paiement')),
                ('reference_paiement', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('TERMINEE', 'Complété'), ('ECHOUEE', 'Échoué'), ('REMBOURSE', 'Remboursé')], default='EN_ATTENTE', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_transaction', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de transaction')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('agence', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='accounts.agence')),
                ('caissier', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CASHIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_traitees', to=settings.AUTH_USER_MODEL)),
                ('client', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='transactions_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction de Tickets',
                'verbose_name_plural': 'Transactions de Tickets',
                'ordering': ['-date_transaction'],
                'indexes': [models.Index(fields=['numero_transaction'], name='transaction_numero__1a2e5b_idx'), models.Index(fields=['client', 'date_transaction'], name='transaction_client__dbaa50_idx'), models.Index(fields=['statut'], name='transaction_statut_f08c5e_idx')],
            },
        ),
    ]
