# Generated by Django 6.0.2 on 2026-02-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionticket',
            name='dernier_ticket',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro du dernier ticket'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='premier_ticket',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numéro du premier ticket'),
        ),
    ]
