# Generated by Django 6.0.2 on 2026-02-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_alter_transactionticket_dernier_ticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionticket',
            name='montant_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Montant total'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='subvention_totale',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Subvention totale'),
        ),
    ]
