# Generated by Django 6.0.2 on 2026-02-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transactionticket_montant_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionticket',
            name='mode_paiement',
            field=models.CharField(choices=[('ESPECES', 'Espèces'), ('CARTE', 'Carte bancaire'), ('MOBILE', 'Mobile Money'), ('VIREMENT', 'Virement')], default='ESPECES', max_length=20, verbose_name='Mode de paiement'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='nombre_tickets',
            field=models.IntegerField(default=1, verbose_name='Nombre de tickets'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Prix unitaire'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='subvention_par_ticket',
            field=models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Subvention par ticket'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='valide_de',
            field=models.DateField(blank=True, null=True, verbose_name='Valide à partir du'),
        ),
        migrations.AlterField(
            model_name='transactionticket',
            name='valide_jusqu_a',
            field=models.DateField(blank=True, null=True, verbose_name="Valide jusqu'au"),
        ),
    ]
