# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'agence")),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('type_agence', models.CharField(choices=[('SIEGE', 'Siège'), ('REGIONALE', 'Agence Régionale'), ('LOCALE', 'Agence Locale'), ('SUCCURSALE', 'Succursale')], default='LOCALE', max_length=20, verbose_name="Type d'agence")),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('ville', models.CharField(max_length=100, verbose_name='Ville')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Région')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('telephone', models.CharField(max_length=17, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('fax', models.CharField(blank=True, max_length=17, verbose_name='Fax')),
                ('capacite_max_employes', models.IntegerField(blank=True, default=100, null=True, verbose_name="Capacité maximale d'employés")),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_ouverture', models.DateField(blank=True, null=True, verbose_name="Date d'ouverture")),
                ('date_fermeture', models.DateField(blank=True, null=True, verbose_name='Date de fermeture')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Agence',
                'verbose_name_plural': 'Agences',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom de la direction')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('telephone', models.CharField(blank=True, max_length=17, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('est_active', models.BooleanField(default=True, verbose_name='Active')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créée le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifiée le')),
            ],
            options={
                'verbose_name': 'Direction',
                'verbose_name_plural': 'Directions',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_email', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('notification_sms', models.BooleanField(default=False, verbose_name='Notifications SMS')),
                ('langue', models.CharField(default='fr', max_length=10, verbose_name='Langue')),
                ('contact_urgence_nom', models.CharField(blank=True, max_length=200, verbose_name="Contact d'urgence")),
                ('contact_urgence_telephone', models.CharField(blank=True, max_length=17, verbose_name="Téléphone d'urgence")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Adresse email')),
                ('nom_utilisateur', models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name="Nom d'utilisateur")),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. 8 à 15 chiffres autorisés.", regex='^\\+?1?\\d{8,15}$')], verbose_name='Téléphone')),
                ('genre', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Féminin')], max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('type_utilisateur', models.CharField(choices=[('CLIENT', 'Client (Employé)'), ('CAISSIER', 'Caissier'), ('GESTIONNAIRE_RESTAURANT', 'Gestionnaire de restaurant'), ('SUPER_ADMIN', 'Super administrateur')], default='CLIENT', max_length=30, verbose_name="Type d'utilisateur")),
                ('matricule', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Matricule')),
                ('departement', models.CharField(blank=True, max_length=100, verbose_name='Département')),
                ('poste', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profils/', verbose_name='Photo de profil')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('est_personnel', models.BooleanField(default=False, verbose_name='Personnel')),
                ('est_verifie', models.BooleanField(default=False, verbose_name='Vérifié')),
                ('est_super_utilisateur', models.BooleanField(default=False, verbose_name='Super utilisateur')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date d'inscription")),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_inscription'],
            },
        ),
    ]
