# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='restaurant_gere',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestionnaires', to='restaurants.restaurant'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='superieur_hierarchique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordonnes', to=settings.AUTH_USER_MODEL, verbose_name='Supérieur hiérarchique'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='agence',
            name='agence_parente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_agences', to='accounts.agence', verbose_name='Agence parente'),
        ),
        migrations.AddField(
            model_name='agence',
            name='responsable',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur__in': ['SUPER_ADMIN', 'CAISSIER']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences_gerees', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='agence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='accounts.agence', verbose_name='Agence'),
        ),
        migrations.AddField(
            model_name='direction',
            name='directeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur__in': ['SUPER_ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions_dirigees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='agence',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agences', to='accounts.direction', verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employes', to='accounts.direction', verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='profilutilisateur',
            name='utilisateur',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['code'], name='accounts_ag_code_1464ea_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['ville'], name='accounts_ag_ville_2e598b_idx'),
        ),
        migrations.AddIndex(
            model_name='agence',
            index=models.Index(fields=['est_active'], name='accounts_ag_est_act_f859f0_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['email'], name='accounts_ut_email_7bd265_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['matricule'], name='accounts_ut_matricu_25ca8d_idx'),
        ),
        migrations.AddIndex(
            model_name='utilisateur',
            index=models.Index(fields=['type_utilisateur'], name='accounts_ut_type_ut_c4f9fb_idx'),
        ),
    ]
