# Generated by Django 6.0.2 on 2026-02-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agence',
            name='capacite_max_employes',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='code_postal',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='fax',
        ),
        migrations.RemoveField(
            model_name='agence',
            name='notes',
        ),
        migrations.AlterField(
            model_name='agence',
            name='type_agence',
            field=models.CharField(choices=[('SIEGE', 'Siège'), ('REGIONALE', 'Agence Régionale'), ('LOCALE', 'Agence Locale')], default='LOCALE', max_length=20, verbose_name="Type d'agence"),
        ),
    ]
