# Generated by Django 6.0.2 on 2026-02-25 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_agence_capacite_max_employes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='type_utilisateur',
            field=models.CharField(choices=[('CLIENT', 'Client (Employé)'), ('CAISSIER', 'Caissier'), ('GESTIONNAIRE_RESTAURANT', 'Gestionnaire de restaurant'), ('ADMIN', 'Administrateur')], default='CLIENT', max_length=30, verbose_name="Type d'utilisateur"),
        ),
    ]
