# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Code')),
                ('image_qr', models.ImageField(blank=True, null=True, upload_to='qrcodes/', verbose_name='Image QR')),
                ('donnees_tickets', models.JSONField(default=dict, verbose_name='Données des tickets')),
                ('est_valide', models.BooleanField(default=True, verbose_name='Valide')),
                ('expire_le', models.DateTimeField(verbose_name='Expire le')),
                ('est_utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('utilise_le', models.DateTimeField(blank=True, null=True, verbose_name='Utilisé le')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('utilisateur', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='codes_qr', to=settings.AUTH_USER_MODEL)),
                ('utilise_par_restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_qr_scannes', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Code QR',
                'verbose_name_plural': 'Codes QR',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Numéro du ticket')),
                ('statut', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('CONSOMME', 'Consommé'), ('EXPIRE', 'Expiré'), ('ANNULE', 'Annulé')], default='DISPONIBLE', max_length=20, verbose_name='Statut')),
                ('date_consommation', models.DateTimeField(blank=True, null=True, verbose_name='Consommé le')),
                ('valide_de', models.DateField(verbose_name='Valide à partir du')),
                ('valide_jusqua', models.DateField(verbose_name="Valide jusqu'au")),
                ('prix_paye', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Prix payé')),
                ('montant_subventionne', models.DecimalField(decimal_places=2, default=1500, max_digits=10, verbose_name='Montant subventionné')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('proprietaire', models.ForeignKey(limit_choices_to={'type_utilisateur': 'CLIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
                ('restaurant_consommateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_consommes', to='restaurants.restaurant')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-date_creation'],
            },
        ),
    ]
