# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_genere', to='transactions.transactionticket'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='valide_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'GESTIONNAIRE_RESTAURANT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_valides', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='codeqr',
            index=models.Index(fields=['code'], name='tickets_cod_code_bd3ed2_idx'),
        ),
        migrations.AddIndex(
            model_name='codeqr',
            index=models.Index(fields=['utilisateur', 'est_valide'], name='tickets_cod_utilisa_bfe27c_idx'),
        ),
        migrations.AddIndex(
            model_name='codeqr',
            index=models.Index(fields=['expire_le'], name='tickets_cod_expire__0c2cec_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['numero_ticket'], name='tickets_tic_numero__84ef8e_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['proprietaire', 'statut'], name='tickets_tic_proprie_be502a_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['valide_de', 'valide_jusqua'], name='tickets_tic_valide__31cdaa_idx'),
        ),
    ]
