# Generated by Django 6.0.2 on 2026-02-21 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valide_par',
            field=models.ForeignKey(blank=True, limit_choices_to={'type_utilisateur': 'RESTAURANT_MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
