# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeleEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('type_modele', models.CharField(choices=[('BIENVENUE', 'Bienvenue'), ('CONFIRMATION_ACHAT', "Confirmation d'achat"), ('CONFIRMATION_CONSOMMATION', 'Confirmation de consommation'), ('NOTIFICATION_PROGRAMMATION', 'Notification de programmation'), ('NOTIFICATION_MENU', 'Notification de menu'), ('REINITIALISATION_MDP', 'Réinitialisation de mot de passe'), ('VERIFICATION_COMPTE', 'Vérification de compte'), ('PERSONNALISE', 'Personnalisé')], max_length=50, verbose_name='Type')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('corps_texte', models.TextField(verbose_name='Corps (texte)')),
                ('corps_html', models.TextField(blank=True, verbose_name='Corps (HTML)')),
                ('variables_disponibles', models.JSONField(default=dict, verbose_name='Variables disponibles')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': "Modèle d'Email",
                'verbose_name_plural': "Modèles d'Email",
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('COMPTE', 'Compte'), ('ACHAT', 'Achat'), ('CONSOMMATION', 'Consommation'), ('PROGRAMMATION', 'Programmation'), ('MENU', 'Menu'), ('SYSTEME', 'Système'), ('RAPPEL', 'Rappel')], max_length=20, verbose_name='Type')),
                ('priorite', models.CharField(choices=[('BASSE', 'Basse'), ('MOYENNE', 'Moyenne'), ('HAUTE', 'Haute'), ('URGENTE', 'Urgente')], default='MOYENNE', max_length=10, verbose_name='Priorité')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('lien', models.URLField(blank=True, verbose_name='Lien')),
                ('texte_lien', models.CharField(blank=True, max_length=100, verbose_name='Texte du lien')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('lu_le', models.DateTimeField(blank=True, null=True, verbose_name='Lu le')),
                ('envoyer_email', models.BooleanField(default=False, verbose_name='Envoyer par email')),
                ('email_envoye', models.BooleanField(default=False, verbose_name='Email envoyé')),
                ('email_envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='Email envoyé le')),
                ('envoyer_sms', models.BooleanField(default=False, verbose_name='Envoyer par SMS')),
                ('sms_envoye', models.BooleanField(default=False, verbose_name='SMS envoyé')),
                ('sms_envoye_le', models.DateTimeField(blank=True, null=True, verbose_name='SMS envoyé le')),
                ('modele_lie', models.CharField(blank=True, max_length=100, verbose_name='Modèle lié')),
                ('id_lie', models.IntegerField(blank=True, null=True, verbose_name='ID lié')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('destinataire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['destinataire', 'est_lu'], name='notifs_noti_destina_22923e_idx'), models.Index(fields=['cree_le'], name='notifs_noti_cree_le_e6774f_idx')],
            },
        ),
    ]
