# Generated by Django 6.0.2 on 2026-02-11 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JourFerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du jour férié')),
                ('date', models.DateField(verbose_name='Date')),
                ('recurrent', models.BooleanField(default=False, verbose_name='Récurrent chaque année')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
            ],
            options={
                'verbose_name': 'Jour Férié',
                'verbose_name_plural': 'Jours Fériés',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='ParametresSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_min_par_transaction', models.IntegerField(default=1, help_text='Nombre minimum de tickets pouvant être achetés en une transaction', verbose_name='Nombre minimum de tickets par transaction')),
                ('tickets_max_par_transaction', models.IntegerField(default=20, help_text='Nombre maximum de tickets pouvant être achetés en une transaction', verbose_name='Nombre maximum de tickets par transaction')),
                ('transactions_max_par_mois', models.IntegerField(default=1, help_text="Nombre maximum de transactions qu'un client peut effectuer par mois", verbose_name='Nombre maximum de transactions par mois')),
                ('prix_ticket', models.DecimalField(decimal_places=2, default=500, help_text="Prix payé par l'employé pour un ticket", max_digits=10, verbose_name='Prix du ticket')),
                ('prix_repas_complet', models.DecimalField(decimal_places=2, default=2000, help_text="Prix complet d'un repas", max_digits=10, verbose_name='Prix complet du repas')),
                ('subvention_ticket', models.DecimalField(decimal_places=2, default=1500, help_text='Montant subventionné par la mutuelle par ticket', max_digits=10, verbose_name='Montant de la subvention')),
                ('duree_validite_qr_code_minutes', models.IntegerField(default=3, help_text="Durée en minutes avant expiration d'un QR code", verbose_name='Durée de validité du QR code (minutes)')),
                ('autoriser_programmation_hebdomadaire', models.BooleanField(default=True, verbose_name='Autoriser programmation hebdomadaire')),
                ('autoriser_programmation_mensuelle', models.BooleanField(default=True, verbose_name='Autoriser programmation mensuelle')),
                ('jours_avance_min_programmation', models.IntegerField(default=1, help_text="Nombre de jours d'avance requis pour programmer un restaurant", verbose_name="Jours d'avance minimum pour programmation")),
                ('envoyer_notifications_achat', models.BooleanField(default=True, verbose_name="Envoyer notifications d'achat")),
                ('envoyer_notifications_consommation', models.BooleanField(default=True, verbose_name='Envoyer notifications de consommation')),
                ('envoyer_notifications_programmation', models.BooleanField(default=True, verbose_name='Envoyer notifications de programmation')),
                ('envoyer_notifications_menu', models.BooleanField(default=True, verbose_name='Envoyer notifications de menu')),
                ('email_notifications_expediteur', models.EmailField(default='noreply@lonab.com', max_length=254, verbose_name="Email d'envoi des notifications")),
                ('nom_entreprise', models.CharField(default='LONAB', max_length=200, verbose_name="Nom de l'entreprise")),
                ('nom_mutuelle', models.CharField(default='MUTRALO', max_length=200, verbose_name='Nom de la mutuelle')),
                ('email_support', models.EmailField(default='support@lonab.com', max_length=254, verbose_name='Email de support')),
                ('telephone_support', models.CharField(blank=True, max_length=17, verbose_name='Téléphone de support')),
                ('mode_maintenance', models.BooleanField(default=False, help_text='Active le mode maintenance (accès limité)', verbose_name='Mode maintenance')),
                ('message_maintenance', models.TextField(blank=True, help_text='Message affiché pendant la maintenance', verbose_name='Message de maintenance')),
                ('cree_le', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('modifie_le', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('modifie_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parametres_modifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paramètres Système',
                'verbose_name_plural': 'Paramètres Système',
            },
        ),
        migrations.CreateModel(
            name='JournalAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATION', 'Création'), ('MODIFICATION', 'Modification'), ('SUPPRESSION', 'Suppression'), ('CONNEXION', 'Connexion'), ('DECONNEXION', 'Déconnexion'), ('ACHAT', 'Achat'), ('CONSOMMATION', 'Consommation'), ('REMBOURSEMENT', 'Remboursement')], max_length=20, verbose_name='Action')),
                ('modele', models.CharField(max_length=100, verbose_name='Modèle')),
                ('objet_id', models.IntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('description', models.TextField(verbose_name='Description')),
                ('adresse_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('donnees_anciennes', models.JSONField(blank=True, null=True, verbose_name='Anciennes données')),
                ('donnees_nouvelles', models.JSONField(blank=True, null=True, verbose_name='Nouvelles données')),
                ('cree_le', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Créé le')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journaux_audit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Journal d'Audit",
                'verbose_name_plural': "Journaux d'Audit",
                'ordering': ['-cree_le'],
                'indexes': [models.Index(fields=['utilisateur', 'cree_le'], name='settings_jo_utilisa_38e22f_idx'), models.Index(fields=['action', 'cree_le'], name='settings_jo_action_fa6a8e_idx'), models.Index(fields=['modele', 'objet_id'], name='settings_jo_modele_fd9873_idx')],
            },
        ),
    ]
